export const data = [
  {
    id: 1,
    title: "Car",
    price: 10,
    company: "Toyata",
    info: "one of the best car",
    inCart: false,
    count: 1,
  },
  {
    id: 2,
    title: "Bike",
    price: 20,
    company: "Honda",
    info: "one of the best Bike",
    inCart: false,
    count: 1,
  },
  {
    id: 3,
    title: "Book",
    price: 50,
    company: "History Book",
    info: "Good Book",
    inCart: false,
    count: 1,
  },
  {
    id: 4,
    title: "Sofa",
    price: 40,
    company: "BeTeck",
    info: "Best Sofa",
    inCart: false,
    count: 1,
  },
  {
    id: 5,
    title: "Shoe",
    price: 25,
    company: "Nike",
    info: "Quality Shoe",
    inCart: false,
    count: 1,
  },
];
